MYSQL:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'Carbia1143'
  name: "minecraft"

Game-Stats:
  XP_KILL: 20
  XP_WIN: 150
  COINS_KILL: 30
  COINS_WIN: 200

Levels: ##DEBE ESTAR ORDENADO POR NIVEL
  Rewards:
    0:
      Color: "&7"
      Commands:
        - ""
    15:
      Color: "&c"
      Commands:
        - ""
    50:
      Color: "&b"
      Commands:
        - ""
  Max-Level: 100

Chat-Format: "%color_level%(%level%) %rank% &f%player%: %msg%"

Command-Shop-Permission: "aqua set %player% permission %permission%"

Tab-Format:
  Team: "%team_color%%rank% %player%"
  Solo: "%rank% %player%"
  Lobby: "%rank% %player%"

Main-Spawn:
  World: '-'
  Location: '0, 0, 0'

## LO UNICO EDITABLE ES EL NOMBRE DE LOS EFECTOS Y SU PRECIOS
## NO SE PUEDEN AGREGAR NI QUITAR
Kill-Effect:
  NONE:
    Name: "Ninguno"
    Price: 0
    ID: "PAPER"
  COLD:
    Name: "Nieve"
    Price: 0
    ID: "SNOWBALL"
  LAVA:
    Name: "Lava"
    Price: 0
    ID: "LAVA_BUCKET"
  VORTEX:
    Name: "Vortex"
    Price: 0
    ID: "BRICKS"
  CLOUD:
    Name: "Nubes"
    Price: 0
    ID: "BONE_MEAL"
  HEART:
    Name: "Corazones"
    Price: 0
    ID: "APPLE"
  COOKIE:
    Name: "Cookies"
    Price: 0
    ID: "COOKIE"
  COIN:
    Name: "Monedas"
    Price: 0
    ID: "GOLD_NUGGET"
  MEAT:
    Name: "Comida"
    Price: 0
    ID: "COOKED_BEEF"
  RAINBOW:
    Name: "Arcoiris"
    Price: 0
    ID: "RED_WOOL"
  RAYO:
    Name: "Rayo"
    Price: 0
    ID: "WATER_BUCKET"

Win-Effect:
  NONE:
    Name: "Ninguno"
    Price: 0
    ID: "PAPER"

Trails:
  NONE:
    Name: "Ninguno"
    Price: 0
    ID: "PAPER"
  CRIT:
    Name: "Critico"
    Price: 0
    ID: "DIAMOND_SWORD"
  FLAME:
    Name: "Flamas"
    Price: 0
    ID: "HORN_CORAL_FAN"
  LAVA:
    Name: "Lava"
    Price: 0
    ID: "LAVA_BUCKET"
  NOTE:
    Name: "Notas"
    Price: 0
    ID: "NOTE_BLOCK"
  REDSTONE:
    Name: "Redstone"
    Price: 0
    ID: "REDSTONE"
  SLIME:
    Name: "Slime"
    Price: 0
    ID: "SLIME_BLOCK"
  WATER_BUBBLE:
    Name: "Burbujas"
    Price: 0
    ID: "GHAST_TEAR"
  HEART:
    Name: "Corazones"
    Price: 0
    ID: "FERMENTED_SPIDER_EYE"


Cages-Type-Prices:
  ESFERA: 1000
  PIRAMIDE: 1000
  DOMO: 1000

Cages-Materials:
  ####################################
  #GLASS: <- ID DEL BLOQUE
  #"Cristal" <- NOMBRE QUE SE MOSTRARÃ
  ####################################
  GLASS: ### NO BORRAR ####
    Name: "Cristal"
    Price: 0
  ####################################
  TNT:
    Name: "Dinamita"
    Price: 0
  WHITE_STAINED_GLASS:
    Name: "Cristal blanco"
    Price: 1000
  BLACK_WOOL:
    Name: "Lana negra"
    Price: 1000

Scoreboards:
  IN_GAME:
    Title: "&e&lSKYWARS"
    Lines:
      - "&7%arena_mode% (%date%)"
      - "&7"
      - "&fTiempo: &d%arena_time_formatted%"
      - "&7"
      - "&fMapa: &a&n%arena_name%"
      - "&fEscenario: &e%arena_scenario%"
      - "&fRollback: &b%arena_rollback_formatted%"
      - "&7"
      - "&fJugadores vivos: &e%arena_players%"
      - "&fAsesinatos: &c%arena_player_kills%"
      - "&7"
      - "&emc.felipe221.com"
  LOBBY:
    Title: "&e&lSKYWARS"
    Lines:
      - "&7"
      - "&fNivel: &e%stats_level%"
      - "&fExperiencia &b%stats_xp%/%stats_next_level_xp%"
      - "&7"
      - "&fTrail: &a%stats_trail%"
      - "&fCaja: &e%stats_cage_type%"
      - "&fEfecto de victoria: &6%stats_win_effect%"
      - "&7"
      - "&emc.felipe221.com"
  ENDING:
    Title: "&e&lSKYWARS"
    Lines:
      - "&fMapa: %arena%"
      - ""
  RESTARTING:
    Title: "&e&lSKYWARS"
    Lines:
      - "&fMapa: %arena%"
      - ""
  WAITING:
    Title: "&e&lSKYWARS"
    Lines:
      - "&7%arena_mode% (%date%)"
      - "&7"
      - "&fMapa: &a&n%arena_name%"
      - "&fEscenario: &e%arena_scenario%"
      - "&7"
      - "&fJugadores: &b%arena_players%/%arena_min% &7(minimos)"
      - "&7"
      - "&emc.felipe221.com"
  STARTING:
    Title: "&e&lSKYWARS"
    Lines:
      - "&7%arena_mode% (%date%)"
      - "&7"
      - "&fMapa: &a&n%arena_name%"
      - "&fEscenario: &e%arena_scenario%"
      - "&7"
      - "&fComenzando en &c&n%arena_seconds%&f segundos"
      - "&7"
      - "&emc.felipe221.com"